### ISSUE TITLE
Where is the clang_wrapper.py

### ISSUE THREAD

**Issue by terenceli** [google/kmsan#12]
Hi, 
I'm a newbie of kmsan.
Could anyone told me where is the clang_wrapper.py so I can build the kernel.
Thanks

**Comment by dvyukov** [comment]
Hi,

@ramosian-glider is OOO for some time.
But I think you don't need clang_wrapper.py now. Just build with patched clang. You can get one here:
https://github.com/google/syzkaller/blob/master/docs/syzbot.md#crash-does-not-reproduce

**Comment by ramosian-glider** [comment]
Hi there,
Dmitry is right, you don't need clang_wrapper.py anymore. If you really want to experiment with it, feel free to pick the latest version using ```git log clang_wrapper.py```

**Comment by sgzeng** [comment]
Have you succeeded building the kernel? I always get the following error:

make[2]: *** No rule to make target 'net/netfilter/xt_TCPMSS.o', needed by 'net/netfilter/built-in.o'.  Stop.
scripts/Makefile.build:583: recipe for target 'net/netfilter' failed
make[1]: *** [net/netfilter] Error 2
Makefile:1061: recipe for target 'net' failed
make: *** [net] Error 2

**Comment by dvyukov** [comment]
Yes. Try taking kernel config from here https://syzkaller.appspot.com/text?tag=KernelConfig&id=6627248707860932248
And compiler from here https://storage.googleapis.com/syzkaller/clang-kmsan-329060.tar.gz
Then it's pretty much running `make`.

**Comment by darran-kelinske-fivestars** [comment]
Did you find a fix? I'm experiencing this building for a Lenovo Tablet
