### ISSUE TITLE
__msan_warning_32 name is confusing

### ISSUE THREAD

**Issue by dvyukov** [google/kmsan#21]
Just spent some time looking at a report assuming that 32 in `__msan_warning_32` means uninit value size, similar to __asan_load1/2/4/8. But it did not make sense because the line number pointed to a comparison of a 64-bit value.
I think we need to rename `__msan_warning_32` to `__msan_warning_orig` to remove any potential reference to variable sizes.

**Comment by ramosian-glider** [comment]
Even better, we can rename it to plain `__msan_warning()`
I thought it will be a bad idea to have `__msan_warning()` in the kernel and the userspace have different prototypes, but on the second thought it doesn't matter.

**Comment by ramosian-glider** [comment]
This is fixed long ago.
