### ISSUE TITLE
Consider using direct shadow mapping for virtual memory

### ISSUE THREAD

**Issue by ramosian-glider** [google/kmsan#23]
We've come up with a more-or-less viable scheme for direct mapping of shadow and origin memory to kernel memory.
Right now KMSAN stores pointers to shadow and origin pages in `struct page` for each page of physical memory. For virtual memory, we try to find the corresponding physical pages (this is possible for VM_ALLOC and VM_MAP mappings, but not for VM_IOREMAP ones) and operate on them. This approach has the following drawbacks:

- the necessity to make non-uniform checks for different types of pointers (`vmalloc_to_page()` for `vmalloc()` and modules, `virt_to_page` for pages);
- potential problems with accesses to virtual addresses crossing page boundaries (the underlying shadow pages may not be adjacent);
- problems allocating metadata pages for kernel text and data (page_alloc can only allocate 2^n pages, which is inconvenient);
- missing support for ioremap mappings.

The idea is to carve some space from vmalloc/ioremap area, which currently occupies 32 TB (could be also possible to use the KASAN shadow area, which is another 16TB), and use that to allocate shadow and origin pages for virtual memory ranges in the virtual memory itself.

We could also use virtual memory for physical pages, but they take 64 TB, so we'll probably have to reduce that area as well.

**Comment by tapaswenipathak** [comment]
Hi @ramosian-glider: writing. I think most points are done.

**Comment by ramosian-glider** [comment]
After several unsuccessful attempts to implement direct shadow mapping over the past years I think we can live with the existing scheme.
