### ISSUE TITLE
Cann't disable KMSAN

### ISSUE THREAD

**Issue by daydayup40** [google/kmsan#49]
Why I disabled the CONFIG_KMSAN, but I still got KMSAN report by running the kernel with syzkaller

**Comment by ramosian-glider** [comment]
Did you rebuild the kernel after disabling CONFIG_KMSAN?

**Comment by daydayup40** [comment]
Yes. I did these step
1. git clone https://github.com/google/kmsan/
2. cp the config grom syzkaller in:
https://github.com/google/syzkaller/blob/master/dashboard/config/upstream-kmsan.config
3. disable the CONFIG_KMSAN
4. follow the build steps of https://github.com/google/kmsan/
5. run the kernel with the recent syzkaller
6. I got some KMSAN report by syzkaller
Is here anything wrong?

**Comment by dvyukov** [comment]
How did you disable it? What is your resulting .config? What report did you get?

**Comment by daydayup40** [comment]
Sorry, I forgot to modify one parameter in syzkaller .cfg.
