### ISSUE TITLE
When to trigger the check of KMSAN?

### ISSUE THREAD

**Issue by OpenStacksh** [google/kmsan#52]
There is an MSAN example, the code is like this:
`#include <stdio.h>`
`int main() {`
`  int a = 1;`
`  int b;`
`  int c = a + b;`
`  printf("c:%d\n", c);`
`}`
use clang to compile the code:
`clang -fsanitize=memory -fPIE -pie -fno-omit-frame-pointer -g test.c -o test`
**but, the result is like this, No MSAN Report**
`c:1200630145`
**So, why? Why is there no trigger the check?**

**Comment by OpenStacksh** [comment]
There is an MSAN example, the code is like this:
`#include <stdio.h>`
`int main() {`
`  int a = 1;`
`  int b;`
`  int c = a + b;`
`  printf("c:%d\n", c);`
`}`
use clang to compile the code:
`clang -fsanitize=memory -fPIE -pie -fno-omit-frame-pointer -g test.c -o test`
**but, the result is like this, No MSAN Report**
`c:1200630145`
**So, why? Why is there no trigger the check?**

**Comment by dvyukov** [comment]
You seem to be interested in the user-space MSAN, not KMSAN (linux kernel tool).
MSAN project is https://github.com/google/sanitizers and the mailing list for questions is https://groups.google.com/forum/#!forum/memory-sanitizer

**Comment by OpenStacksh** [comment]
@dvyukov ,thank you for your answer!
I am interested in both MSAN and KMSAN. I am currently learning the MSAN.But I think both of them have similarities. So I would like to ask, what is the trigger mechanism for kmsan? When is the check triggered?
Thanks!

**Comment by dvyukov** [comment]
This is the paper with internal details of memorysanitizer:
https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/43308.pdf
If you have further questions, please ask on https://groups.google.com/forum/#!forum/memory-sanitizer. It has the right people.

**Comment by OpenStacksh** [comment]
Thanks. @dvyukov
