### ISSUE TITLE
Compiler lacks asm-goto support

### ISSUE THREAD

**Issue by OpenStacksh** [google/kmsan#58]
I compile the kernel according to the web page([https://github.com/google/kmsan](https://github.com/google/kmsan))
The version of clang is:

> Android (dev based on r346389c) clang version 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf643d27dbca1bb228957008617) (https://android.googlesource.com/toolchain/llvm 3c393fe7a7e13b0fba4ac75a01aa683d7a5b11cd) (based on LLVM 8.0.7svn)
> Target: x86_64-unknown-linux-gnu
> Thread model: posix

However, when I compiled the kernel, this error occurred :
**Compiler lacks asm-goto support.
arch/x86/Makefile:301: recipe for target 'checkbin' failed.**

How to solve this problem?

**Comment by ramosian-glider** [comment]
I believe this is solved now with the latest Clang. Please reopen if you think otherwise.
