### ISSUE TITLE
What needs to be done to enable KMSAN to support arm?

### ISSUE THREAD

**Issue by OpenStacksh** [google/kmsan#62]
Right now the instrumentation pass supports x86_64 only.
What needs to be done to enable KMSAN to support arm?
llvm version : 8.0.7

**Comment by ramosian-glider** [comment]
Most of the code is arch-agnostic. You'll probably need to port the following stuff:
 - calls to functions from kmsan_entry.c from arch/x86/entry/entry_64.S
 - hooks for copy_{to,from}_user() in uaccess.h
 - 847e109a2c5e9be6123394261bb78de8d273d676 ("kmsan: x86: sync metadata pages on page fault")
 - enable CONFIG_GENERIC_CSUM (and probably other configs that replace handwritten assembly routines with C code)

I don't have an ARM64 device at hand to test the port, but I'm happy to review and take decent patches, feel free to send pull requests.

I also encourage you to use a more recent LLVM revision (I'm building KMSAN with a 10.0.0 trunk)

**Comment by OpenStacksh** [comment]
What does clang need to modify to support arm64? Right now the instrumentation pass supports x86_64 only.

**Comment by ramosian-glider** [comment]
I believe we are now in a far better position to support ARM64 (not ARM32, sorry).
Clang's MemorySanitizer pass supports it long ago, so one just needs some driver changes to allow using KMSAN with aarch64.
As for the kernel part, the patches to be released in 6.1 are split in a way that should make porting quite straightforward.
I might give it a shot in 2023, but patches are always welcome.
