### ISSUE TITLE
recipe for target 'vmlinux' failed?

### ISSUE THREAD

**Issue by SamuelZOU** [google/kmsan#73]
I'm attempting to build a latest kmsan kernel, but then halted when it got this message:

  AR      drivers/built-in.a
  GEN     .version
  CHK     include/generated/compile.h
  UPD     include/generated/compile.h
  CC      init/version.o
  AR      init/built-in.a
  LD      vmlinux.o
  MODPOST vmlinux.o
  MODINFO modules.builtin.modinfo
  LD      .tmp_vmlinux1
kernel/panic.o: In function `__msan_memset':
kmsan/./include/linux/string.h:362: undefined reference to `__write_overflow'
Makefile:1078: recipe for target 'vmlinux' failed
make: *** [vmlinux] Error 1

# clang --version
clang version 10.0.0 (https://github.com/llvm/llvm-project.git d052a578de58cbbb638cbe2dba05242d1ff443b9)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin

kmsan# git log
commit 1ab36d3d8b8cf9923e20a96ce4485ca05397db96
Author: Alexander Potapenko <glider@google.com>
Date:   Thu Dec 19 11:29:58 2019 +0100

    kmsan: add doc comments to kmsan-checks.h

Any help?

**Comment by ramosian-glider** [comment]
Hi Samuel,

Is this bug still reproducible? a407139a45b400e7020c152dd20d4ac13137d717 should have probably fixed it.
If the problem persists, can you please share the config you're using?

And sorry for the delay - I somehow missed this bug report.

**Comment by SamuelZOU** [comment]
> Hi Samuel,
> 
> Is this bug still reproducible? [a407139](https://github.com/google/kmsan/commit/a407139a45b400e7020c152dd20d4ac13137d717) should have probably fixed it.
> If the problem persists, can you please share the config you're using?
> 
> And sorry for the delay - I somehow missed this bug report.

It's OK now, thanks a lot.
