### ISSUE TITLE
Any docs to introduce how to build KMSAN on my own kernel

### ISSUE THREAD

**Issue by horseFucker123** [google/kmsan#81]
My kernel version 4.19,so could I build my own kernel with KMSAN?

**Comment by ramosian-glider** [comment]
There are two options: you could either use the kmsan-v4.19 branch as is (you might need to build with a specific Clang version from that times - no idea if it's going to work with the newest one). Be prepared to face numerous bugs in the tool itself.

Another one is to take that branch, but replace the contents of mm/kmsan with the runtime implementation from today's master. This of course won't work out of the box, you'll need to spend some time fitting the new runtime to the old kernel.

**Comment by horseFucker123** [comment]
> There are two options: you could either use the kmsan-v4.19 branch as is (you might need to build with a specific Clang version from that times - no idea if it's going to work with the newest one). Be prepared to face numerous bugs in the tool itself.
> 
> Another one is to take that branch, but replace the contents of mm/kmsan with the runtime implementation from today's master. This of course won't work out of the box, you'll need to spend some time fitting the new runtime to the old kernel.

got it,thanks,I'll try
