### ISSUE TITLE
Compile kmsan with clang-9 with -O2 ERROR

### ISSUE THREAD

**Issue by zizhiyoumu-fuzz** [google/kmsan#84]
While I use clang-9 to compile Variable parameter function(such as f(char * fmt,...)) with -O2, I found error as below:
 <eof> parser at end of file
 Per-module optimization passes
Running pass 'Function Pass Manager' on module 'kernel/linux-4.14/init/do_mounts.c'.
Running pass 'Combine redundant instructions' on function '@f'

I try -O0, it is OK.
Why?
If I still want to compile it with -O2, how to deal with it?
Thanks

**Comment by dvyukov** [comment]
Hi @zizhiyoumu-fuzz,
I think clang-9 is too old and is not supported with KMSAN. Not sure what is the minimal clang, but somewhere around version 11/12.

**Comment by ramosian-glider** [comment]
Yes, as a rule of the thumb please try the latest Clang before reporting bugs.
Even if something is wrong with clang-9 (and it is, since the compiler is never supposed to crash), we cannot fix it retrospectively.
