### ISSUE TITLE
Why do we need to sync metadata in x86_32 page faults?

### ISSUE THREAD

**Issue by shownlin** [google/kmsan#91]
This patch [3f1e2c7](https://github.com/google/kmsan/commit/3f1e2c7a9099c1ed32c67f12cdf432ba782cf51f#) add some KMSAN-related code to the function arch_sync_kernel_mappings,
 but this function should only be used in x86_32.

The text inside arch/x86/mm/fault.c: [172](https://github.com/google/kmsan/blob/3f1e2c7a9099c1ed32c67f12cdf432ba782cf51f/arch/x86/mm/fault.c#L172) - [351](https://github.com/google/kmsan/blob/3f1e2c7a9099c1ed32c67f12cdf432ba782cf51f/arch/x86/mm/fault.c#L351) is only compiled when CONFIG_X86_32 is defined.
Doesn't KMSAN only work in x86_64?

**Comment by ramosian-glider** [comment]
Good catch! Let me see how this sneaked into the code.

**Comment by ramosian-glider** [comment]
This happened in 2020 when switching from kmsan-5.7-rc4 to kmsan-5.8-rc5, where upstream fault handling changed, and I failed to notice that this part became 32-bit-only. Somehow it was also missed during the code reviews last year.

Please let me know what I should write in the Reported-by: tag if you want credit for this :)

**Comment by shownlin** [comment]
Please feel free to add
Reported-by: Qun-Wei Lin <qun-wei.lin@mediatek.com>
